"""initial schema — analysis_sessions + all feature/score/report tables

Revision ID: 0001
Revises:
Create Date: 2026-07-14
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written (not autogenerated) — see db/models.py module docstring for why.
# Enums are created explicitly so both tables that reference `session_state`
# (analysis_sessions.state and analysis_sessions.failed_state) share the same
# Postgres type instead of Alembic trying to create it twice.

# create_type=False on both: table creation would otherwise also try to
# auto-create these types (SQLAlchemy's before_create hook fires whenever an
# Enum column is present), which collides with the explicit `.create()`
# calls below and raises "type already exists". With create_type=False,
# only the explicit `.create()`/`.drop()` calls in upgrade()/downgrade()
# manage the type's lifecycle.
evaluation_mode = postgresql.ENUM(
    "presentation", "interview", name="evaluation_mode", create_type=False
)
session_state = postgresql.ENUM(
    "empty",
    "slide_uploaded",
    "slide_analyzing",
    "slide_analyzed",
    "resume_uploaded",
    "resume_analyzing",
    "resume_analyzed",
    "waiting_for_video",
    "video_uploaded",
    "video_analyzing",
    "video_analyzed",
    "feature_fusion",
    "scoring",
    "prompt_building",
    "reasoning",
    "report_generated",
    "completed",
    "failed",
    name="session_state",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    evaluation_mode.create(bind, checkfirst=True)
    session_state.create(bind, checkfirst=True)

    op.create_table(
        "analysis_sessions",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("mode", evaluation_mode, nullable=False),
        sa.Column("state", session_state, nullable=False, server_default="empty"),
        sa.Column("language", sa.String(length=8), nullable=False, server_default="vi"),
        sa.Column("resume_file_path", sa.String(length=1024), nullable=True),
        sa.Column("slide_file_path", sa.String(length=1024), nullable=True),
        sa.Column("video_file_path", sa.String(length=1024), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("failed_state", session_state, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "resume_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("avg_words_per_page", sa.Float(), nullable=False),
        sa.Column("headings", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("education", sa.JSON(), nullable=False),
        sa.Column("experience", sa.JSON(), nullable=False),
        sa.Column("projects", sa.JSON(), nullable=False),
        sa.Column("font_size_min", sa.Float(), nullable=False, server_default="0"),
        sa.Column("font_size_max", sa.Float(), nullable=False, server_default="0"),
        sa.Column("font_size_avg", sa.Float(), nullable=False, server_default="0"),
        sa.Column("distinct_fonts", sa.JSON(), nullable=False),
        sa.Column("keyword_density", sa.Float(), nullable=False, server_default="0"),
        sa.Column("action_verb_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("quantified_achievement_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("section_completeness", sa.Float(), nullable=False, server_default="0"),
        sa.Column("contact_info_present", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("length_appropriateness", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "slide_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("slide_count", sa.Integer(), nullable=False),
        sa.Column("slides", sa.JSON(), nullable=False),
        sa.Column("image_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("chart_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("table_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fonts", sa.JSON(), nullable=False),
        sa.Column("colors", sa.JSON(), nullable=False),
        sa.Column("average_text_length", sa.Float(), nullable=False, server_default="0"),
        sa.Column("text_density_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("visual_richness_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("consistency_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("notes_usage_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("title_presence_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("structure_balance_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "video_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("duration_sec", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("height", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sampled_frame_count", sa.Integer(), nullable=False),
        sa.Column("brightness_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("brightness_std", sa.Float(), nullable=False, server_default="0"),
        sa.Column("contrast_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("motion_score_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("motion_score_std", sa.Float(), nullable=False, server_default="0"),
        sa.Column("scene_cut_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("blur_score_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "speech_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("sample_rate", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("duration_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("pitch_mean_hz", sa.Float(), nullable=False, server_default="0"),
        sa.Column("pitch_std_hz", sa.Float(), nullable=False, server_default="0"),
        sa.Column("pitch_min_hz", sa.Float(), nullable=False, server_default="0"),
        sa.Column("pitch_max_hz", sa.Float(), nullable=False, server_default="0"),
        sa.Column("voiced_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("tempo_bpm", sa.Float(), nullable=False, server_default="0"),
        sa.Column("rms_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("rms_std", sa.Float(), nullable=False, server_default="0"),
        sa.Column("mfcc_mean", sa.JSON(), nullable=False),
        sa.Column("mfcc_std", sa.JSON(), nullable=False),
        sa.Column("chroma_mean", sa.JSON(), nullable=False),
        sa.Column("spectral_centroid_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("spectral_bandwidth_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("spectral_rolloff_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("zcr_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("zcr_std", sa.Float(), nullable=False, server_default="0"),
        sa.Column("silence_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("total_silence_sec", sa.Float(), nullable=False, server_default="0"),
        sa.Column("silent_region_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("transcript_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("language", sa.String(length=16), nullable=False, server_default=""),
        sa.Column("segments", sa.JSON(), nullable=False),
        sa.Column("average_confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("words_per_minute", sa.Float(), nullable=False, server_default="0"),
        sa.Column("word_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "transcript_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "speech_feature_id",
            sa.Uuid(),
            sa.ForeignKey("speech_features.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("word_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sentence_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("vocabulary_diversity", sa.Float(), nullable=False, server_default="0"),
        sa.Column("repeated_words", sa.JSON(), nullable=False),
        sa.Column("filler_word_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("filler_word_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("grammar_issue_estimate", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("has_opening", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("has_body", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("has_conclusion", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("has_call_to_action", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("topic_consistency", sa.Float(), nullable=False, server_default="0"),
        sa.Column("estimated_cefr", sa.String(length=4), nullable=False, server_default="A1"),
        sa.Column("keyword_coverage", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "emotion_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("emotion_timeline", sa.JSON(), nullable=False),
        sa.Column("emotion_distribution", sa.JSON(), nullable=False),
        sa.Column("dominant_emotion", sa.String(length=16), nullable=False, server_default="neutral"),
        sa.Column("emotion_consistency", sa.Float(), nullable=False, server_default="0"),
        sa.Column("emotion_confidence_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("positive_emotion_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "face_mesh_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("frames_analyzed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("faces_detected_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("blink_rate_per_min", sa.Float(), nullable=False, server_default="0"),
        sa.Column("eye_openness_mean", sa.Float(), nullable=False, server_default="0"),
        sa.Column("eye_contact_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("head_pose_pitch_std", sa.Float(), nullable=False, server_default="0"),
        sa.Column("head_pose_yaw_std", sa.Float(), nullable=False, server_default="0"),
        sa.Column("head_pose_roll_std", sa.Float(), nullable=False, server_default="0"),
        sa.Column("head_movement_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("face_stability_ratio", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "unified_features",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("professionalism", sa.Float(), nullable=False, server_default="0"),
        sa.Column("presentation_density", sa.Float(), nullable=False, server_default="0"),
        sa.Column("communication_confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("visual_engagement", sa.Float(), nullable=False, server_default="0"),
        sa.Column("voice_confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("presentation_readiness", sa.Float(), nullable=False, server_default="0"),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.Column("fusion_engine_version", sa.String(length=32), nullable=False),
        sa.Column("fused_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "score_results",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("resume_score", sa.Integer(), nullable=True),
        sa.Column("slide_score", sa.Integer(), nullable=True),
        sa.Column("speech_score", sa.Integer(), nullable=True),
        sa.Column("transcript_score", sa.Integer(), nullable=True),
        sa.Column("emotion_score", sa.Integer(), nullable=True),
        sa.Column("eye_contact_score", sa.Integer(), nullable=True),
        sa.Column("voice_confidence_score", sa.Integer(), nullable=True),
        sa.Column("presentation_score", sa.Integer(), nullable=True),
        sa.Column("communication_score", sa.Integer(), nullable=True),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("scoring_engine_version", sa.String(length=32), nullable=False),
        sa.Column("scored_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "session_id",
            sa.Uuid(),
            sa.ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("weaknesses", sa.JSON(), nullable=False),
        sa.Column("improvement_plan", sa.JSON(), nullable=False),
        sa.Column("presentation_feedback", sa.Text(), nullable=False, server_default=""),
        sa.Column("interview_feedback", sa.Text(), nullable=False, server_default=""),
        sa.Column("interview_questions", sa.JSON(), nullable=False),
        sa.Column("suggestions", sa.JSON(), nullable=False),
        sa.Column("reasoning_engine_name", sa.String(length=64), nullable=False),
        sa.Column("reasoning_engine_version", sa.String(length=64), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=True),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("reports")
    op.drop_table("score_results")
    op.drop_table("unified_features")
    op.drop_table("face_mesh_features")
    op.drop_table("emotion_features")
    op.drop_table("transcript_features")
    op.drop_table("speech_features")
    op.drop_table("video_features")
    op.drop_table("slide_features")
    op.drop_table("resume_features")
    op.drop_table("analysis_sessions")

    bind = op.get_bind()
    session_state.drop(bind, checkfirst=True)
    evaluation_mode.drop(bind, checkfirst=True)
